export const NATIONALITIES = [
  'Afganistán',
  'Aland',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Anguila',
  'Antártida',
  'Antigua y Barbuda',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaiyán',
  'Bahamas',
  'Bangladés',
  'Barbados',
  'Baréin',
  'Bélgica',
  'Belice',
  'Benín',
  'Bermudas',
  'Bielorrusia',
  'Bolivia',
  'Bonaire, San Eustaquio y Saba',
  'Bosnia y Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunéi',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Bután',
  'Cabo Verde',
  'Camboya',
  'Camerún',
  'Canadá',
  'Catar',
  'Chad',
  'Chile',
  'China',
  'Chipre',
  'Colombia',
  'Comoras',
  'Corea del Norte',
  'Corea del Sur',
  'Costa de Marfil',
  'Costa Rica',
  'Croacia',
  'Cuba',
  'Curazao',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Árabes Unidos',
  'Eritrea',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estados Unidos',
  'Estonia',
  'Etiopía',
  'Filipinas',
  'Finlandia',
  'Fiyi',
  'Francia',
  'Gabón',
  'Gambia',
  'Georgia',
  'Ghana',
  'Gibraltar',
  'Granada',
  'Grecia',
  'Groenlandia',
  'Guadalupe',
  'Guam',
  'Guatemala',
  'Guayana Francesa',
  'Guernsey',
  'Guinea',
  'Guinea-Bisáu',
  'Guinea Ecuatorial',
  'Guyana',
  'Haití',
  'Honduras',
  'Hong Kong',
  'Hungría',
  'India',
  'Indonesia',
  'Irak',
  'Irán',
  'Irlanda',
  'Isla Bouvet',
  'Isla de Man',
  'Isla de Navidad',
  'Islandia',
  'Islas Caimán',
  'Islas Cocos',
  'Islas Cook',
  'Islas Feroe',
  'Islas Georgias del Sur y Sandwich del Sur',
  'Islas Heard y McDonald',
  'Islas Malvinas',
  'Islas Marianas del Norte',
  'Islas Marshall',
  'Islas Pitcairn',
  'Islas Salomón',
  'Islas Turcas y Caicos',
  'Islas Ultramarinas Menores de los Estados Unidos',
  'Islas Vírgenes Británicas',
  'Islas Vírgenes de los Estados Unidos',
  'Israel',
  'Italia',
  'Jamaica',
  'Japón',
  'Jersey',
  'Jordania',
  'Kazajistán',
  'Kenia',
  'Kirguistán',
  'Kiribati',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letonia',
  'Líbano',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Macao',
  'Macedonia del Norte',
  'Madagascar',
  'Malasia',
  'Malaui',
  'Maldivas',
  'Mali',
  'Malta',
  'Marruecos',
  'Martinica',
  'Mauricio',
  'Mauritania',
  'Mayotte',
  'México',
  'Micronesia',
  'Moldavia',
  'Mónaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Mozambique',
  'Birmania',
  'Namibia',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Níger',
  'Nigeria',
  'Niue',
  'Isla Norfolk',
  'Noruega',
  'Nueva Caledonia',
  'Nueva Zelanda',
  'Omán',
  'Países Bajos',
  'Pakistán',
  'Palaos',
  'Palestina',
  'Panamá',
  'Papúa Nueva Guinea',
  'Paraguay',
  'Perú',
  'Polinesia Francesa',
  'Polonia',
  'Portugal',
  'Puerto Rico',
  'Reino Unido',
  'República Árabe Saharaui Democrática',
  'República Centroafricana',
  'República Checa',
  'República del Congo',
  'República Democrática del Congo',
  'República Dominicana',
  'Reunión',
  'Ruanda',
  'Rumania',
  'Rusia',
  'Samoa',
  'Samoa Americana',
  'San Bartolomé',
  'San Cristóbal y Nieves',
  'San Marino',
  'San Martín',
  'San Pedro y Miquelón',
  'San Vicente y las Granadinas',
  'Santa Elena, Ascensión y Tristán de Acuña',
  'Santa Lucía',
  'Santo Tomé y Príncipe',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Singapur',
  'Siria',
  'Somalia',
  'Sri Lanka',
  'Suazilandia',
  'Sudáfrica',
  'Sudán',
  'Sudán del Sur',
  'Suecia',
  'Suiza',
  'Surinam',
  'Svalbard y Jan Mayen',
  'Tailandia',
  'Taiwán (República de China)',
  'Tanzania',
  'Tayikistán',
  'Territorio Británico del Océano Índico',
  'Tierras Australes y Antárticas Francesas',
  'Timor Oriental',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad y Tobago',
  'Túnez',
  'Turkmenistán',
  'Turquía',
  'Tuvalu',
  'Ucrania',
  'Uganda',
  'Uruguay',
  'Uzbekistán',
  'Vanuatu',
  'Ciudad del Vaticano',
  'Venezuela',
  'Vietnam',
  'Wallis y Futuna',
  'Yemen',
  'Yibuti',
  'Zambia',
  'Zimbabue',
];

export const DOCUMENT_TYPES_BY_NATIONALITY: Record<string, string[]> = {
  Colombia: [
    'Cédula de Ciudadanía (CC)',
    'Cédula de Extranjería (CE)',
    'Tarjeta de Identidad (TI)',
    'Pasaporte',
  ],
  México: [
    'Clave Única de Registro de Población (CURP)',
    'Registro Federal de Contribuyentes (RFC)',
    'Credencial para Votar (INE/IFE)',
    'Pasaporte',
  ],
  Perú: [
    'Documento Nacional de Identidad (DNI)',
    'Carné de Extranjería',
    'Pasaporte',
  ],
  Chile: ['Rol Único Nacional (RUN o RUT)', 'Cédula de Identidad', 'Pasaporte'],
  Argentina: [
    'Documento Nacional de Identidad (DNI)',
    'CUIT/CUIL (para trámites fiscales o laborales)',
    'Pasaporte',
  ],
  Ecuador: ['Cédula de Identidad', 'Pasaporte', 'Cédula de Extranjería'],
  Uruguay: ['Cédula de Identidad', 'Pasaporte'],
  Paraguay: ['Cédula de Identidad Civil', 'Pasaporte'],
  Bolivia: ['Cédula de Identidad', 'Pasaporte'],
  Panamá: [
    'Cédula de Identidad Personal',
    'Pasaporte',
    'Cédula de Extranjería',
  ],
  'Costa Rica': [
    'Documento Nacional de Identidad (DNI)',
    'Documento de Identificación de Extranjeros (DIMEX)',
    'Pasaporte',
  ],
  'República Dominicana': ['Cédula de Identidad y Electoral', 'Pasaporte'],
  'El Salvador': ['Documento Único de Identidad (DUI)', 'Pasaporte'],
  Guatemala: ['Documento Personal de Identificación (DPI)', 'Pasaporte'],
  Honduras: ['Documento Nacional de Identificación (DNI)', 'Pasaporte'],
  Nicaragua: ['Cédula de Identidad', 'Pasaporte'],
};

export const POSITIONS = [
  'Presidente',
  'Administrador',
  'Tesorero',
  'Contador',
  'Vocal',
  'Abogado',
];

export const HEADQUARTER_TYPES = [
  'Conjunto Residencial',
  'Edificio',
  'Casa',
  'Bodega',
  'Parqueadero',
  'Departamento',
];
